var app = angular.module("myApp",['pascalprecht.translate']);

app.config(["$translateProvider", function($translateProvider){
  var fr_translations = {
    "language" : "Selected Language Spanish",
    "greeting" : "Bienvenida Dinesh",
    "Envoyez_de_largent" : "Envoyez de l'argent",
    "comment_ca_marche"  : "Comment ça marche",
    "Connexion" : "Connexion",
    "Inscription" : "Inscription",
    "Envoyez_de_largent_maintenant" : "Envoyez de l'argent maintenant",
    "Envoyez_de_largent_vers_Cameroun" : "ENVOYEZ DE L'ARGENT VERS LE CAMEROUN DIRECTEMENT SUR",
    "Nos_atouts" : "Nos atouts",
    "Simplicite" : "Simplicité",
    "Simplicite_details" : "Effectuez vos transactions en ligne en toute facilité et clarté.",
    "Rapidite" : "Rapidité",
    "Rapidite_details" : "Le destinataire reçoit les fonds en quelques secondes.",
    "Securite" : "Sécurité",
    "Securite_details" : "Réalisez vos opérations sans risque et en toute confiance.",
    "Moindre_cout" : "Moindre coût",
    "Moindre_cout_details" : "Nous appliquons les commissions les plus basses du marché.",
    "popup_Simplicite" : "Nos plateformes web et mobile permettent de gérer vos transferts de l'appareil de votre choix où que vous soyez. Nous vous assurons la flexibilité nécessaire pour maîtriser votre flux de trésorerie internationale.",
    "popup_Close" : "Fermez",
    "popup_Rapidite" : "Le destinataire reçoit les fonds en quelques secondes.",
    "popup_Moindre_cout" : "Éliminez les frais excessifs qu'offre la concurrence. Gagnez plus sur chaque transaction grâce à la faible marge de nos taux . L'argent que vous économisez est un bénéfice net.",
    "popup_Securite" : "Réalisez vos opérations sans risque et en toute confiance.",
    "Service_client" : "SERVICE CLIENT",
    "Contactez_nous" : "Contactez-nous",
    "Envoyer_un_Message" : "Envoyer un Message",
    "Ecrivez_nous" : "Ecrivez nous, nous vous répondrons dans un délais de 2 heures.",
    "comment_ca_marche_step_one" : "Notre service permet d’effectuer un dépôt sur un compte Mobile Money au Cameroun (MTN Mobile Money ou Orange Money) en réglant par carte de crédit (Visa, MasterCard etc.). Les montants vont de 5.000 FCFA (environ 7,60 euros) à 100.000 FCFA (environ 152,40 euros) en tranches de 5.000 FCFA (5.000 FCFA, 10.000 FCFA, 15.000 FCFA, 20.000 FCFA ……… 100.000 FCFA).",
    "comment_ca_marche_step_two" : "Où que vous vous trouviez sur les 5 continents, avec le service IPercash, vous déposez de l’argent sur le compte Mobile Money d’un membre de votre famille ou d’un proche au Cameroun. Celui-ci pourra effectuer des achats directement en réglant par Mobile Money ou alors retirer cet argent en liquidités auprès de l’un des 45.000 points de vente au Cameroun. L’opération est exécutée immédiatement, le compte mobile money est crédité instantanément.",
    "prérequis_pour_le_service" : "Pour utiliser notre service, il faut donc :",
    "prérequis_un_pour_le_service" : "Disposer d’une carte de crédit",
    "prérequis_deux_pour_le_service" : "Etre sûr du numéro de téléphone du destinataire",
    "prérequis_trois_pour_le_service" : "Etre sûr que le destinataire dispose d’un compte mobile money actif sur le numéro en question",
    "comment_ca_marche_premiere_remarque" : "IPercash est bien moins cher que tous ces concurrents et bénéficie du réseau des points de vente du Mobile Money dont le nombre de point de présence est dix fois plus élevé que celui des points de vente des services concurrents. Le service est opérationnel 24h24, 7j/7.",
    "comment_ca_marche_step_three" : "Pour une première opération",
    "comment_ca_marche_detail_one" : "Rendez-vous à la page d’accueil et cliquez sur le menu INSCRIPTION en haut à gauche. Renseignez le formulaire de création de compte.",
    "comment_ca_marche_detail_two_section_one" : "Et cliquez sur ENREGISTREZ. Un code de vérification vous sera alors envoyé dans votre boite mail.",
    "comment_ca_marche_detail_two_section_two" : "Inscrivez le code de vérification dans le champ prévu et cliquez sur VERIFIEZ afin d’activer votre compte.",
    "comment_ca_marche_detail_two_section_three" : "La vérification effectuée et le compte activé, vous êtes automatiquement dirigés vers la page des transferts. Vous êtes connecté lorsque votre nom apparaît en haut à droite ainsi qu’un menu déroulant sous votre nom.",
    "comment_ca_marche_detail_two_section_four" : "Choisissez le montant en FCFA à envoyer dans le menu déroulant (de 5000 FCFA à 100 000 FCFA). Le détail des frais apparait, le montant exact que pourra retirer le bénéficiaire apparait également.",
    "comment_ca_marche_detail_two_section_five" : "Après validation, vous serez dirigé vers le formulaire d’envoi. Vous indiquerez le nom et le prénom du bénéficiaire ainsi que deux fois son numéro de téléphone mobile money.",
    "comment_ca_marche_detail_two_section_six" : "Vous aurez à confirmer le récapitulatif des données renseignées",
    "comment_ca_marche_detail_two_section_seven" : "Après validation, vous serez orienté vers la page de paiement de Payplug notre prestataire de services de paiement de grande renommée. PayPlug sécurise entièrement la transaction ; votre numéro de carte de crédit nous restera inconnu.",
    "comment_ca_marche_detail_two_section_eight" : "Entrez le numéro de votre carte de crédit, la date d’expiration ainsi que le chiffre confidentiel.",
    "comment_ca_marche_detail_two_section_nine" : "Le paiement sera confirmé par votre historique de transactions un fois validé. Un courrier de confirmation sera également envoyé dans votre boite mail.",
    "Formulaire_creation_compte" : "Formulaire de création de compte",
    "Formulaire_creation_compte_nom" : "Nom",
    "Formulaire_creation_compte_prenom" : "Prenom",
    "Formulaire_creation_compte_pays" : "Pays de résidence",
    "Formulaire_creation_compte_ville" : "Ville",
    "Formulaire_creation_compte_email" : "Email",
    "Formulaire_creation_compte_password" : "Mot de passe",
    "Formulaire_creation_compte_confirmpassword" : "Comfirmez votre mot de passe",
    "Formulaire_creation_compte_terms_first_part" : "J'accepte les ",
    "Formulaire_creation_compte_terms_second_part" : "Termes et conditions",
    "Formulaire_creation_compte_register" : "Enregistrez",
    "Formulaire_creation_compte_meconnecter" : "Me connecter",
    "Formulaire_creation_compte_alreadyaccount" : "j'ai déjà un compte",
    "Transfert_simplicite_title" : "Simplicité",
    "Transfert_simplicite_detail" : "Effectuez vos transaction en ligne en toute facilité et clarté.",
    "Transfert_rapidite_title" : "Rapidité",
    "Transfert_rapidite_detail" : "Le destinataire reçoit les fonds en quelques secondes.",
    "Transfert_securite_title" : "Sécurité",
    "Transfert_securite_detail" : "Réalisez  vos opérations sans risque et en toute confiance.",
    "Transfert_moindrecout_title" : "Moindre coût",
    "Transfert_moindrecout_detail" : "Nous appliquons les commissions les plus basses du marché.",
    "Transfert_form_title" : "Envoyer de l'argent en ligne",
    "Transfert_form_choisir_service" : "Choisir un Service",
    "Transfert_form_firstservice" : "Transfert d'argent",
    "Transfert_form_secondservice" : "Achat de crédit téléphonique",
    "Transfert_form_amountCFA" : "Montant en Franc CFA",
    "Transfert_form_amount" : "Montant:",
    "Transfert_form_frais" : "Frais:",
    "Transfert_form_total" : "Total à payer:",
    "Transfert_form_reçu" : "Le bénéficiaire reçoit:",
    "Transfert_form_envoyer" : "Envoyer",
    "Footer_form_name" : "Votre nom",
    "Footer_form_email" : "Votre email",
    "Footer_form_message" : "Votre message",
    "Footer_form_telwatsapp" : "Votre numéro de téléphone whatsapp",
    "Footer_form_motdepasse" : "Votre mot de passe",
    "Footer_form_motdepasseoublie" : "Mot de passe oublié?",
    "Footer_politique" : "Politique de Confidentialité",
    "Footer_term_condition" : "Termes et conditions",
    "Footer_conditionuser" : "Conditions d'utilisation",
    "TransfertIndex_titre" : "Formulaire d'envoi d'argent",
    "TransfertIndex_soustitre" : "Envoyez de l'argent à vos proches en toute confiance.",
    "TransfertIndex_apropos" : "A Propos de vous",
    "TransfertIndex_destinataire" : "Destinataire",
    "TransfertIndex_vosinformation" : "Vos Informations",
    "TransfertIndex_nom" : "Nom",
    "TransfertIndex_prenom" : "Prenom",
    "TransfertIndex_info_destinataire" : "Informations concernant le destinataire",
    "TransfertIndex_infonom_destinataire" : "Nom du bénéficiaire ",
    "TransfertIndex_infoprenom_destinataire" : "Prénom du bénéficiaire",
    "TransfertIndex_infotelephone_destinataire" : "Téléphone du bénéficiaire ",
    "TransfertIndex_confirmerinfotelephone_destinataire" : "Confirmez Téléphone ",
    "TransfertIndex_champobligatoire" : "obligatoire ",
    "TransfertIndex_suivant" : "Suivant",
    "TransfertIndex_confirmez" : "Confirmez",
    "TransfertIndex_precedent" : "Précédent",
    "Document_pdf_confidentialite" : "confidentialite.pdf",
    "Document_pdf_termes_et_condition" : "termes_et_condition.pdf",
    "Document_pdf_condition_utilisation" : "condition_utilisation.pdf"
  }

  var en_translations = {
    "language" : "Selected Language English",
    "greeting" : "Welcome Dinesh",
    "Envoyez_de_largent" : "Send money",
    "comment_ca_marche"  : "How it works",
    "Connexion" : "Log in",
    "Inscription" : "Register",
    "Envoyez_de_largent_maintenant" : "Send money now",
    "Envoyez_de_largent_vers_Cameroun" : "Send Money to Cameroon directly on",
    "Nos_atouts" : "Our strengths",
    "Simplicite" : "Simplicity",
    "Simplicite_details" : "Your transactions online with ease and clarity.",
    "Rapidite" : "Speed",
    "Rapidite_details" : "The recipient receives the funds in a matter of seconds.",
    "Securite" : "Safety and security",
    "Securite_details" : "Carry out your transactions without risk and with complete confidence.",
    "Moindre_cout" : "Lowest cost",
    "Moindre_cout_details" : "We offer the lowest transfer fees on the market.",
    "popup_Simplicite" : "Our web and mobile platforms allow you to manage your transfers from the device of your choice wherever you are. We provide you with the flexibility to control your international cash flow.",
    "popup_Close" : "Close",
    "popup_Rapidite" : "The recipient receives the funds in a matter of seconds.",
    "popup_Moindre_cout" : "Eliminate the excessive costs offered by the competition. Send more for less on each transaction thanks to the low margin of our rates. The money you save is a net benefit.",
    "popup_Securite" : "Carry out your transactions without risk and with complete confidence.",
    "Service_client" : "CUSTOMER SERVICE",
    "Contactez_nous" : "Contact Us",
    "Envoyer_un_Message" : "Send us a message",
    "Ecrivez_nous" : "Write to us, we will get back to you within 2 hours.",
    "comment_ca_marche_step_one" : "Our service allows you to make a deposit on a Mobile Money account in Cameroon (MTN Mobile Money or Orange Money) by paying by credit card (Visa, MasterCard etc.).  The amounts range from 5,000 FCFA (about 7,60 euros) to 100,000 FCFA (about 152,40 euros) in tranches of 5,000 FCFA (5,000 FCFA, 10,000 FCFA, 15,000 FCFA, 20,000 FCFA ......... 100,000 FCFA).",
    "comment_ca_marche_step_two" : "Wherever you are on all continents, with the IPercash service, you can deposit money on the mobile money account of a family member or friend in Cameroon. The recipient can make purchases directly by paying with Mobile Money or withdraw the money in cash from one of the 45,000 points of sale in Cameroon. The operation is executed immediately, the mobile money account is instantly credited.",
    "prérequis_pour_le_service" : "To use our service, you must:",
    "prérequis_un_pour_le_service" : "Have a credit card",
    "prérequis_deux_pour_le_service" : "Be sure of the recipient's mobile phone number",
    "prérequis_trois_pour_le_service" : " Be sure that the recipient has an active mobile money account on numb",
    "comment_ca_marche_premiere_remarque" : "IPercash is much cheaper than all its competitors and benefits from the network of Mobile Money points of sale with a presence that is twenty times higher than that of competing service points of sale.  The service is operational 24 hours a day, 7 days a week.",
    "comment_ca_marche_step_three" : " For a first operation",
    "comment_ca_marche_detail_one" : " Go to the home page and click on the REGISTER menu at the top left.  Fill out the account creation form.",
    "comment_ca_marche_detail_two_section_one" : "And click on REGISTER.  A verification code will be sent to your mailbox.",
    "comment_ca_marche_detail_two_section_two" : "Enter the verification code in the field provided and click ACTIVATE to activate your account",
    "comment_ca_marche_detail_two_section_three" : "Once the account is verified and activated, you will automatically be directed to the transfer page.  You are logged in when your name appears at the top right with a drop-down menu under your name",
    "comment_ca_marche_detail_two_section_four" : "Choose the amount in FCFA to send in the drop-down menu (from 5000 FCFA to 100 000 FCFA).  The details of the costs, as well as the exact amount that the beneficiary can withdraw will appears for validation.",
    "comment_ca_marche_detail_two_section_five" : " After validation, you will be directed to the submission form.  You will indicate the beneficiary's first and last name and enter his/her mobile money number twice.",
    "comment_ca_marche_detail_two_section_six" : " You will be prompted to confirm the summary of the data entered",
    "comment_ca_marche_detail_two_section_seven" : "Once confirmed, you will be directed to the payment page of Purepay our renowned payment service provider.  Purepay fully secures the transaction;  your credit card number will remain unknown to us.",
    "comment_ca_marche_detail_two_section_eight" : " Enter the number of your credit card, the expiration date and the confidential number.",
    "comment_ca_marche_detail_two_section_nine" : "The payment confirmation will appear in your transaction history once validated and a confirmation email will also be sent to your mailbox.",
    "Formulaire_creation_compte" : "ACCOUNT CREATION FORM",
    "Formulaire_creation_compte_nom" : "Name",
    "Formulaire_creation_compte_prenom" : "First name",
    "Formulaire_creation_compte_pays" : "Country of residency",
    "Formulaire_creation_compte_pays" : "Country of residency",
    "Formulaire_creation_compte_ville" : "City",
    "Formulaire_creation_compte_email" : "Email",
    "Formulaire_creation_compte_password" : "Password",
    "Formulaire_creation_compte_confirmpassword" : "Confirm Password",
    "Formulaire_creation_compte_terms_first_part" : "I accept",
    "Formulaire_creation_compte_terms_second_part" : " the Terms and Conditions",
    "Formulaire_creation_compte_register" : "Register",
    "Formulaire_creation_compte_meconnecter" : "Log in",
    "Formulaire_creation_compte_alreadyaccount" : "I already have an account",
    "Transfert_simplicite_title" : "Simplicity",
    "Transfert_simplicite_detail" : "Make your transactions online with ease and clarity.",
    "Transfert_rapidite_title" : "Speed",
    "Transfert_rapidite_detail" : "The recipient receives the funds in a matter of seconds.",
    "Transfert_securite_title" : "Security",
    "Transfert_securite_detail" : "Carry out your transactions without risk and with complete confidence.",
    "Transfert_moindrecout_title" : "Lowest cost",
    "Transfert_moindrecout_detail" : "We apply the lowest commissions on the market.",
    "Transfert_form_title" : "Send money online",
    "Transfert_form_choisir_service" : "Choose a Service",
    "Transfert_form_firstservice" : "Money Transfert",
    "Transfert_form_secondservice" : "Purchase of telephone credit",
    "Transfert_form_amountCFA" : "Amount in CFA francs",
    "Transfert_form_amount" : "Amount:",
    "Transfert_form_frais" : "Fees:",
    "Transfert_form_total" : "Total to pay:",
    "Transfert_form_reçu" : "The beneficiary receives:",
    "Transfert_form_envoyer" : "Send",
    "Footer_form_name" : "Your name",
    "Footer_form_email" : "Your email",
    "Footer_form_message" : "Your Message",
    "Footer_form_telwatsapp" : "Your wathsapp number",
    "Footer_form_motdepasse" : "Your password",
    "Footer_form_motdepasseoublie" : "Forgot your password?",
    "Footer_politique" : "Privacy policy",
    "Footer_term_condition" : "Terms and conditions",
    "Footer_conditionuser" : "Terms of use",
    "TransfertIndex_titre" : "Send money form",
    "TransfertIndex_soustitre" : "Send money to loved ones with confidence.",
    "TransfertIndex_apropos" : "About you",
    "TransfertIndex_destinataire" : "Recipient",
    "TransfertIndex_vosinformation" : "Your informations",
    "TransfertIndex_nom" : "Last name",
    "TransfertIndex_prenom" : "first name",
    "TransfertIndex_info_destinataire" : "Recipient information Recipient name",
    "TransfertIndex_infonom_destinataire" : "Name of beneficiary",
    "TransfertIndex_infoprenom_destinataire" : "Beneficiary's first name",
    "TransfertIndex_infotelephone_destinataire" : "Beneficiary's phone ",
    "TransfertIndex_confirmerinfotelephone_destinataire" : "Confirm Phone ",
    "TransfertIndex_champobligatoire" : "Required ",
    "TransfertIndex_suivant" : "Next",
    "TransfertIndex_precedent" : "Previous",
    "TransfertIndex_confirmez" : "Confirm",
    "Document_pdf_confidentialite" : "PRIVACY_POLICY.pdf",
    "Document_pdf_termes_et_condition" : "TERMS_AND_CONDITIONS.pdf",
    "Document_pdf_condition_utilisation" : "TERMS_OF_USE.pdf"
  }
  

  
  $translateProvider.translations('en',en_translations);
  
  $translateProvider.translations('fr',fr_translations);
  
  $translateProvider.preferredLanguage('fr');
  //$translateProvider.useLocalStorage();
  //$translateProvider.useMissingTranslationHandlerLog();
  
}]);

app.controller("translateController" ,["$scope","$translate",function($scope,$translate){
  if(localStorage.getItem('lang')){
    $translate.use(localStorage.getItem('lang'));
  }
  $scope.changeLanguage = function(lang){
   localStorage.setItem('lang', lang);
   $translate.use(localStorage.getItem('lang'));
  }
}]);

